# Nombre de la aplicación
spring.application.name=booking-engine

# Puerto del servidor
server.port=8080

# Configuración de PostgreSQL (Docker Container: saas-postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/saas_booking_db
spring.datasource.username=saas_admin
spring.datasource.password=saas_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración Flyway (gestiona el esquema de base de datos)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

# Configuración de Redis (Docker Container: saas-redis)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Formato de Fechas global (ISO-8601)
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSZ
spring.jackson.time-zone=UTC